import { GridState } from './constants'
import type { Story, Task, ProfileMap } from './types'

const now = new Date().toISOString()

export const mockStories: Story[] = [
  {
    id: 12345,
    title: 'Implement user authentication flow',
    state: GridState.PROFILE_ASSIGNMENT,
    profileKey: null,
    worktreePath: null,
    sessionId: null,
    prUrl: null,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12345',
    disabled: false,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12346,
    title: 'Add dashboard analytics widgets',
    state: GridState.PROFILE_ASSIGNMENT,
    profileKey: null,
    worktreePath: null,
    sessionId: null,
    prUrl: null,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12346',
    disabled: false,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12340,
    title: 'Refactor API middleware layer',
    state: GridState.PLAN_APPROVAL,
    profileKey: 'web-app',
    worktreePath: 'C:/repos/web-app-wt1',
    sessionId: 'session-abc-123',
    prUrl: null,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12340',
    disabled: true,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12341,
    title: 'Update notification system',
    state: GridState.PLAN_APPROVAL,
    profileKey: 'backend-svc',
    worktreePath: 'C:/repos/backend-svc-wt1',
    sessionId: 'session-def-456',
    prUrl: null,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12341',
    disabled: false,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12330,
    title: 'Migrate database schema v2',
    state: GridState.TASK_PR_REVIEW,
    profileKey: 'backend-svc',
    worktreePath: 'C:/repos/backend-svc-wt2',
    sessionId: 'session-ghi-789',
    prUrl: null,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12330',
    disabled: false,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12320,
    title: 'Implement search indexing',
    state: GridState.STORY_PR_REVIEW,
    profileKey: 'web-app',
    worktreePath: 'C:/repos/web-app-wt3',
    sessionId: 'session-jkl-012',
    prUrl: 'https://github.com/org/web-app/pull/42',
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12320',
    disabled: false,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12310,
    title: 'Add CSV export feature',
    state: GridState.COMPLETED,
    profileKey: 'web-app',
    worktreePath: null,
    sessionId: 'session-mno-345',
    prUrl: 'https://github.com/org/web-app/pull/38',
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12310',
    disabled: true,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
]

export const mockTasks: Task[] = [
  {
    id: 12331,
    title: 'Create migration script for users table',
    storyId: 12330,
    worktreePath: 'C:/repos/backend-svc-wt3',
    sessionId: 'session-task-001',
    prUrl: 'https://github.com/org/backend-svc/pull/101',
    prMerged: true,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12331',
    disabled: true,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12332,
    title: 'Create migration script for orders table',
    storyId: 12330,
    worktreePath: 'C:/repos/backend-svc-wt4',
    sessionId: 'session-task-002',
    prUrl: 'https://github.com/org/backend-svc/pull/102',
    prMerged: false,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12332',
    disabled: false,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 12333,
    title: 'Update ORM models for new schema',
    storyId: 12330,
    worktreePath: 'C:/repos/backend-svc-wt5',
    sessionId: 'session-task-003',
    prUrl: null,
    prMerged: false,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12333',
    disabled: true,
    prUpdated: false,
    createdAt: now,
    updatedAt: now,
  },
]

export const mockProfiles: ProfileMap = {
  'web-app': {
    repoPath: 'C:/repos/web-app',
    defaultBranch: 'main',
    description: 'Main web application',
  },
  'backend-svc': {
    repoPath: 'C:/repos/backend-svc',
    defaultBranch: 'main',
    description: 'Backend microservice',
  },
  'shared-lib': {
    repoPath: 'C:/repos/shared-lib',
    defaultBranch: 'develop',
    description: 'Shared library package',
  },
}
