import { GridState } from './constants';
import type { ProfileMap, Story, Task } from './types';

const now = new Date().toISOString();

export const mockStories: Story[] = [
  {
    id: 12345,
    title: 'Implement user authentication flow',
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12345',
  },
  {
    id: 12346,
    title: 'Add dashboard analytics widgets',
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12346',
  },
  {
    id: 12330,
    title: 'Migrate database schema v2',
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12330',
  },
];

export const mockTasks: Task[] = [
  // Profile Assignment
  {
    id: 12351,
    title: 'Create login page component',
    storyId: 12345,
    state: GridState.PROFILE_ASSIGNMENT,
    profileKey: null,
    worktreePath: null,
    sessionId: null,
    model: null,
    prUrl: null,
    prMerged: false,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12351',
    disabled: false,
    prUpdated: false,
    completedAt: null,
    errorMessage: null,
    errorAt: null,
    skipCopilot: false,
    createdAt: now,
    updatedAt: now,
  },
  // Task Execution — agent working
  {
    id: 12352,
    title: 'Build analytics chart component',
    storyId: 12346,
    state: GridState.TASK_EXECUTION,
    profileKey: 'web-app',
    worktreePath: 'C:/repos/web-app-wt1',
    sessionId: 'session-abc-123',
    model: 'claude-opus-4.6',
    prUrl: null,
    prMerged: false,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12352',
    disabled: true,
    prUpdated: false,
    completedAt: null,
    errorMessage: null,
    errorAt: null,
    skipCopilot: false,
    createdAt: now,
    updatedAt: now,
  },
  // PR Review
  {
    id: 12331,
    title: 'Create migration script for users table',
    storyId: 12330,
    state: GridState.PR_REVIEW,
    profileKey: 'backend-svc',
    worktreePath: 'C:/repos/backend-svc-wt3',
    sessionId: 'session-task-001',
    model: 'claude-opus-4.6',
    prUrl: 'https://github.com/org/backend-svc/pull/101',
    prMerged: false,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12331',
    disabled: false,
    prUpdated: false,
    completedAt: null,
    errorMessage: null,
    errorAt: null,
    skipCopilot: false,
    createdAt: now,
    updatedAt: now,
  },
  // Completed
  {
    id: 12332,
    title: 'Create migration script for orders table',
    storyId: 12330,
    state: GridState.COMPLETED,
    profileKey: 'backend-svc',
    worktreePath: 'C:/repos/backend-svc-wt4',
    sessionId: 'session-task-002',
    model: 'claude-opus-4.6',
    prUrl: 'https://github.com/org/backend-svc/pull/102',
    prMerged: true,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12332',
    disabled: true,
    prUpdated: false,
    completedAt: now,
    errorMessage: null,
    errorAt: null,
    skipCopilot: false,
    createdAt: now,
    updatedAt: now,
  },
  // Blocked
  {
    id: 12333,
    title: 'Update ORM models for new schema',
    storyId: 12330,
    state: GridState.BLOCKED,
    profileKey: null,
    worktreePath: null,
    sessionId: null,
    model: null,
    prUrl: null,
    prMerged: false,
    azureUrl: 'https://dev.azure.com/org/project/_workitems/edit/12333',
    disabled: false,
    prUpdated: false,
    completedAt: null,
    errorMessage: null,
    errorAt: null,
    skipCopilot: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockProfiles: ProfileMap = {
  'web-app': {
    repoPath: 'C:/repos/web-app',
    defaultBranch: 'main',
    description: 'Main web application',
  },
  'backend-svc': {
    repoPath: 'C:/repos/backend-svc',
    defaultBranch: 'main',
    description: 'Backend microservice',
  },
  'shared-lib': {
    repoPath: 'C:/repos/shared-lib',
    defaultBranch: 'develop',
    description: 'Shared library package',
  },
};
